#:kivy 2.1.0

WidgetExamples:

<WidgetExamples>:
    cols: 3
    ToggleButton:
        text: 'OFF'
        on_state: root.onToggleMe(self)

        size_hint: 0.4, 1















    Button:
        text: 'Count'
        font_name: 'Fonts/LBRITE.TTF'
        on_press: root.onClickMe()
        font_size: 30
    Label:
        text: root.txt
        font_name: 'Fonts/DS-DIGIT.TTF'
        font_size: 100
        color: 1, 0.5, 0, 1
    





